Sit position fix
webaverse/app pull request #1845
Opened 2021-11-22 16:11 UTC by Loryhoof

![sitwip](https://user-images.githubusercontent.com/29487929/142895861-5ce0a020-4d05-4fe0-b5b8-d2586548fa20.png)

2021-11-22 16:12 UTC, Loryhoof commented
https://github.com/webaverse/app/issues/1841

2021-11-22 21:10 UTC, avaer requested changes
Both 1 and 1.4 are incorrect values.

I should work for all avatars and all sittables, with no constants.

2021-11-23 12:21 UTC, Loryhoof commented
changing it from 1.4 to `this.player.avatar.height` and changing the hovercraft's metaversefile's sitOffset to 0.5 works for all avatars. The dragon mount is using the sitbone so doesn't need sitOffset change.

https://github.com/webaverse/hovercraft/pull/3

2021-11-24 02:11 UTC, avaer approved these changes

2021-11-24 02:11 UTC, merged