remove unneeded localPlayer updateds
webaverse/app pull request #2646
Opened 2022-03-22 17:39 UTC by 0reo

closes #2621 

this PR removes the update code which will not be needed once the vrm templates handle that via useFrame.  Currently requires https://github.com/webaverse/totum/pull/86 before it can be merged

2022-03-23 21:33 UTC, 0reo commented
ready for review, https://github.com/webaverse/totum/pull/86 which this depends on is also waiting for review

2022-03-24 20:22 UTC, avaer requested changes
One question.

2022-03-24 20:22 UTC, avaer commented on webaverse.js
> -          playersManager.update(timestamp, timeDiffCapped);
This line is removed and not added in the Torum PR. Where did this go?

2022-04-01 04:44 UTC, avaer requested changes
No comments on the previous review, and the code has not changed.

https://github.com/webaverse/app/pull/2646#r834694958

2022-04-01 04:47 UTC, avaer commented
The Totum PR has been merged but this one has not, so they are desynchronized and I suspect puling `totum` into master at this point would be broken.

2022-04-01 04:50 UTC, avaer commented
Totum PR has been reverted: https://github.com/webaverse/totum/pull/86

So it will need to be submitted and merged synchronously with this one next time.

2022-04-05 16:57 UTC, 0reo commented
new totum PR with useFrame was added to this.  have not recieved any feedback regarding the review notes, but both this and totum should be ready to merge.

2022-04-08 18:00 UTC, 0reo commented
closing this PR as there will be a general change in approach.  will be addressed in a new PR

2022-04-08 18:00 UTC, closed without merging