fix panel bug
webaverse/app pull request #3114
Opened 2022-06-08 02:19 UTC by tcm390

allow the user to select objects in the world and have them show in the object panel.

Reference: https://github.com/webaverse/app/issues/3112

https://user-images.githubusercontent.com/60634884/172517162-5fb33315-7aab-435a-8aa8-8574d3175491.mp4

2022-06-08 11:14 UTC, avaer requested changes
This is close, but I think this update belongs in the `game.js` update loop?

2022-06-08 15:23 UTC, tcm390 commented
> move world object select to game.js

[move world object select to game.js](https://github.com/webaverse/app/pull/3114/commits/7af1fe7adf10680f646ebd85c1ba09f6bab5c386)

2022-06-10 14:41 UTC, tcm390 commented on ai/lore/lore-model.js
> +export * from 'http://localhost/lore-model.js';
Sorry @avaer but it does not in here https://github.com/webaverse/app/pull/3114/files

2022-07-03 03:43 UTC, lalalune commented
Hello @tcm390 is this ready to be pulled in? Could you please resolve the packages/three conflict?
@alisaad673 has this been resviewed?

2022-07-07 21:00 UTC, lalalune commented
@avaer reviewed this, works good

cool if we pull this?

![image](https://user-images.githubusercontent.com/18633264/177870406-8cf734b9-87b2-4f74-832f-5775f1dc9f57.png)

2022-07-08 11:33 UTC, alisaad673 commented
Hey @lalalune  @tcm390  Sorry I missed the review request. 
I have tested this,

 the functionality seems to be working fine, except this one bug:
-While we select any object from world and edit it, After we close the world panel, there still is the pointer for selecting the objects also there is this position pointer too. We are unable to click into the world and unable to move camera direction. This  happens only when we try to close the panel with mouse. Doesn't happens when we close the panel with "Z" key.

https://user-images.githubusercontent.com/35926530/177983287-e120daf7-b1ae-40d3-ac03-1ca4c32a64ff.mp4

https://user-images.githubusercontent.com/35926530/177983775-23bfd5ca-6c31-4a8b-9781-86fd12fd36b6.mp4

2022-07-20 02:02 UTC, lalalune commented
Close in favor of https://github.com/webaverse/app/pull/3262/

2022-07-20 02:02 UTC, closed without merging