Dragon equipped from character panel appears at (0,0,0) instead of the actual position bug
webaverse/app pull request #3448
Opened 2022-08-02 00:09 UTC by tcm390

add `position` parameter to `handleDropUrlToPlayer` function

related: 
https://github.com/webaverse/app/issues/3442
https://github.com/webaverse/dragon-mount/pull/4

Result:

https://user-images.githubusercontent.com/60634884/182265138-c95ed28f-3785-42e9-af55-5aa712b41aa8.mp4

2022-08-02 17:43 UTC, alisaad673 commented
@tcm390 the bug seems fixed, but the equipped dragon in your branch is not appearing at the ground level, instead it appears above the ground.

Equipped dragon in master:

https://user-images.githubusercontent.com/35926530/182438962-2e4faf7a-44f1-43ae-9116-b6719deb6abe.mp4



Equipped dragon in PR:

https://user-images.githubusercontent.com/35926530/182438945-fdefb037-d79b-4de8-876c-01cd6626a504.mp4

2022-08-02 18:10 UTC, tcm390 commented
[sub avatar height](https://github.com/webaverse/app/pull/3448/commits/e3f831367646ddd101af6683ed53d63d50f70898)

2022-08-03 18:47 UTC, alisaad673 commented
Works fine

2022-08-11 21:28 UTC, avaer commented on game.js
> +  async handleDropUrlToPlayer(u, index, position) {
Index is not used so why not remove it? Also with these miscellaneous optional arguments we should use an options object rather than positional args.

2022-08-11 21:28 UTC, avaer requested changes
Recommending code cleanup.

2022-08-11 22:44 UTC, merged