Add cryptoavatars
webaverse/app pull request #3528
Opened 2022-08-06 19:25 UTC by mavisakalyan

## Describe your changes
- Crypto avatars list added to the character select box.
- Character select preview box fixed to the bottom so when you scroll through all the lists it does not scroll with it.
- Changed the show arrow on hover for selecting the characters to just css and removed updateArrowPosition to decrease FPS ( No need to run all those functions for just 1 arrow ).
- Fixed the issue where some characters were facing the other way on preview.
- Fixed the app crashing when certain characters were selected ( problem was that not all models have the Head mesh called exactly "Head" so we modified the code a bit. )
- Styled the select boxes for the CryptoAvatar menu to fit the design better.
## What are the steps for a QA tester to test this pull request?
- Load the scene
- Open the character select menu
- And surf through the newly added CryptoAvatar characters
- Use pagination, hover over the characters and see them in the preview box
- Select the characters and playtest.
## Issue ticket number and link

## Screenshots and/or video

https://user-images.githubusercontent.com/55106546/183263052-12afeccf-24db-45a5-b3d6-e2638aeccb66.mov

## Checklist before requesting a review
- [ + ] I have performed a self-review of my code
- [ + ] I am not adding any irrelevant code or assets
- [ + ] I am only including the changes needed to implement the change
- [ + ] I have playtested and intentionally tried to find error cases but couldn't

2022-08-08 19:17 UTC, avaer commented
Can we get rid of PNG and use SVG?

https://github.com/webaverse/app/pull/3528/files#diff-94bce46600a509ecd3a2f8c05432084ba0e40346ff825454501753c45efdcd8c

2022-08-08 19:53 UTC, avaer commented on src/components/general/character-select/cryptoavatars-loader.js
> +    collectionAddress = '0xc1def47cf1e15ee8c2a92f4e0e968372880d18d1',
These should at least be constants in this file.

2022-08-08 19:54 UTC, avaer commented on src/components/general/character-select/CharacterSelect.jsx
> +        '0xc1def47cf1e15ee8c2a92f4e0e968372880d18d1'
This should be a constant.

2022-08-08 19:54 UTC, avaer commented on src/components/general/character-select/CharacterSelect.jsx
> +    const getCryptoAvatars = async (
This should be in a more abstract util, even if it's just a local `util.js`.

2022-08-08 19:55 UTC, avaer commented on src/components/general/character-select/CharacterSelect.jsx
> +    const [ arrowPosition2, setArrowPosition2 ] = useState(null);
`arrowPosition2` is not used?

2022-08-08 19:56 UTC, avaer commented on src/LightArrow.jsx
> +        left: `75%`,
This could be in the stylesheet. Also, would prefer to use pixel values rather than percentages.

2022-08-08 19:56 UTC, avaer commented
This edits `package-lock.json` and `totum`, which I don't think it should.

2022-08-08 19:57 UTC, avaer requested changes
Overall looks good, but needs more abstraction and refactoring.

2022-08-11 22:52 UTC, mavisakalyan commented
All comments on code cleared ready for review.

2022-08-12 05:36 UTC, avaer commented
Code can’t be trusted since it included irrelevant security related files.

2022-09-07 13:32 UTC, zenkale commented
Issues:
1-The premium avatars are accessible while they shouldn't be:

https://user-images.githubusercontent.com/111510128/188887493-d3f32639-9040-4663-a9ae-eb8c2fe48b33.mp4

2-The previews are going out of bounds of preview area:

https://user-images.githubusercontent.com/111510128/188887949-874a6363-4193-4e17-a737-60ae5f68a2cd.mp4

3-Selecting the options isn't working as expected. For example: choosing the ownership as free use or owned throws these errors, meanwhile the characters in list remain the same.

![image](https://user-images.githubusercontent.com/111510128/188888645-c80f06e3-4817-4a90-90c8-48249441b212.png)

https://user-images.githubusercontent.com/111510128/188888988-4ee8e666-9fb1-4b43-8896-f3b867549288.mp4

4-Selecting the 25 avatars per page option only gets 20 avatars instead of 25:

![image](https://user-images.githubusercontent.com/111510128/188889425-dcc74e7d-7912-46ca-b66f-347835ec4cfd.png)

5-If we select 10, 25 characters per page, the characters appear above the preview of the selected character. Can we fix it so that preview isn't covered?

![image](https://user-images.githubusercontent.com/111510128/188889800-7a2f8548-32fb-4fb4-a055-e83cf8fe648d.png)

6-When we have the openai key set up, some of the characters play the same intro as we have for above upstreet avatars:

https://user-images.githubusercontent.com/111510128/188890441-d934ebe7-20ad-421d-baf5-2296bfa4f5d8.mp4

2022-09-22 11:46 UTC, luixxma commented
Hi, i am going to update this PR with the new nft collection system of our API and fix the problem with premium avatars wich can be selected.

2022-10-02 22:57 UTC, lalalune commented
> Hi, i am going to update this PR with the new nft collection system of our API and fix the problem with premium avatars wich can be selected.

Great. We have the same work earmarked, if you can get to it first, great.

We have this merged and in testing over at: https://github.com/webaverse-studios/app

This is kind of our staging server atm

Gonna close this PR in place of the one we have their.

2022-10-02 22:57 UTC, closed without merging

2022-10-02 22:57 UTC, lalalune commented
> Hi, i am going to update this PR with the new nft collection system of our API and fix the problem with premium avatars wich can be selected.

Great. We have the same work earmarked, if you can get to it first, great.

We have this merged and in testing over at: https://github.com/webaverse-studios/app

This is kind of our staging server atm

Gonna close this PR in place of the one we have their.