precompile heal effect
webaverse/app pull request #3581
Opened 2022-08-10 18:52 UTC by tcm390

precompile heal effect material

Issue:
video1 | video2|
:-------------------------:|:-------------------------:

https://user-images.githubusercontent.com/60634884/183993887-e529ae86-c43b-4f2d-ada5-8765890b17a0.mp4| 

https://user-images.githubusercontent.com/60634884/183993938-068bf085-3f5f-4374-bbb5-f0c7c6d00d8f.mp4

2022-08-11 21:40 UTC, avaer commented on metaverse_modules/heal-effect/index.js
>        let circlePlay = false;
If this is true, why do we need this variable?

2022-08-11 21:41 UTC, avaer requested changes
Code needs cleanup.

2022-08-12 14:04 UTC, alisaad673 commented
Seems to be working fine, there's no hiccup/delay/jitter now on the first time use of heal effect

2022-09-05 17:46 UTC, rondoor124 commented
@tcm390 would you do some code cleanup?

2022-09-05 18:15 UTC, tcm390 commented
> @tcm390 would you do some code cleanup?
[clean code](https://github.com/webaverse/app/pull/3581/commits/00da48541b54570644d38f8ee2a280d78624a0ca)

2022-12-02 22:07 UTC, closed without merging